import {
  AwardIcon,
  BanknoteIcon,
  BookOpenIcon,
  BrainIcon,
  BriefcaseBusinessIcon,
  Building2Icon,
  CalculatorIcon,
  ChartColumnIcon,
  ChartPieIcon,
  ClipboardCheckIcon,
  CodeIcon,
  CogIcon,
  CoinsIcon,
  CpuIcon,
  DatabaseIcon,
  FactoryIcon,
  FileTextIcon,
  FuelIcon,
  GlobeIcon,
  GraduationCapIcon,
  HandshakeIcon,
  HardHatIcon,
  HeartPulseIcon,
  LandmarkIcon,
  LaptopIcon,
  LeafIcon,
  LightbulbIcon,
  MegaphoneIcon,
  MessagesSquareIcon,
  PlaneIcon,
  PresentationIcon,
  ScaleIcon,
  SettingsIcon,
  ShieldCheckIcon,
  ShipIcon,
  ShoppingCartIcon,
  StethoscopeIcon,
  TargetIcon,
  TruckIcon,
  UserCogIcon,
  UsersIcon,
  UtensilsIcon,
  WarehouseIcon,
  WrenchIcon,
  ZapIcon,
  type LucideIcon,
} from "lucide-react";

// Harus sama dengan CATEGORY_ICONS di BE/src/lib/validators/category.ts (BE memvalidasi nama).
export const CATEGORY_ICONS = {
  award: AwardIcon,
  banknote: BanknoteIcon,
  "book-open": BookOpenIcon,
  brain: BrainIcon,
  "briefcase-business": BriefcaseBusinessIcon,
  "building-2": Building2Icon,
  calculator: CalculatorIcon,
  "chart-column": ChartColumnIcon,
  "chart-pie": ChartPieIcon,
  "clipboard-check": ClipboardCheckIcon,
  code: CodeIcon,
  cog: CogIcon,
  coins: CoinsIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  factory: FactoryIcon,
  "file-text": FileTextIcon,
  fuel: FuelIcon,
  globe: GlobeIcon,
  "graduation-cap": GraduationCapIcon,
  handshake: HandshakeIcon,
  "hard-hat": HardHatIcon,
  "heart-pulse": HeartPulseIcon,
  landmark: LandmarkIcon,
  laptop: LaptopIcon,
  leaf: LeafIcon,
  lightbulb: LightbulbIcon,
  megaphone: MegaphoneIcon,
  "messages-square": MessagesSquareIcon,
  plane: PlaneIcon,
  presentation: PresentationIcon,
  scale: ScaleIcon,
  settings: SettingsIcon,
  "shield-check": ShieldCheckIcon,
  ship: ShipIcon,
  "shopping-cart": ShoppingCartIcon,
  stethoscope: StethoscopeIcon,
  target: TargetIcon,
  truck: TruckIcon,
  "user-cog": UserCogIcon,
  users: UsersIcon,
  utensils: UtensilsIcon,
  warehouse: WarehouseIcon,
  wrench: WrenchIcon,
  zap: ZapIcon,
} satisfies Record<string, LucideIcon>;

export type CategoryIconName = keyof typeof CATEGORY_ICONS;

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS) as CategoryIconName[];

export function categoryIcon(name: string | null | undefined): LucideIcon | null {
  return name && name in CATEGORY_ICONS ? CATEGORY_ICONS[name as CategoryIconName] : null;
}
